In [ ]:
# prompt: read a csv to colab

from google.colab import files
import pandas as pd

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
  df = pd.read_csv(fn)
  print(df.head())


Saving NPPE1_Preprocessing1.csv to NPPE1_Preprocessing1 (2).csv
User uploaded file "NPPE1_Preprocessing1 (2).csv" with length 799171 bytes
        CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.82710

In [ ]:
import pandas as pd
df = pd.read_csv("NPPE1_Preprocessing1.csv")
print(df.head())

        CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

  RIVERSIDE  
0        NO  
1        NO  
2        NO  
3        NO  
4        NO  


In [ ]:
df.shape

(4000, 14)

In [ ]:
df['PRICE'].mean()

24.355923220694248

In [ ]:
df[df['RM']>=5].shape

(3953, 14)

In [ ]:
df['PRICE'].sort_values(ascending=False, ignore_index=True).iloc[:10].mean()

52.36590175716407

In [ ]:
df['RM'].unique()

array([ 6.,  7.,  8.,  9., 10., -1.,  5.,  4., 11.])

In [ ]:
df[df['RM']==-1].shape

(40, 14)

In [ ]:
df['RM'].describe()

count    4000.000000
mean        7.044500
std         1.240526
min        -1.000000
25%         6.000000
50%         7.000000
75%         8.000000
max        11.000000
Name: RM, dtype: float64

In [ ]:
df['RM'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 4000 entries, 0 to 3999
Series name: RM
Non-Null Count  Dtype  
--------------  -----  
4000 non-null   float64
dtypes: float64(1)
memory usage: 31.4 KB


In [ ]:
df['AGE'].sort_values(ascending=True).unique()

array([ -2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
        13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
        24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,
        35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,
        46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,
        57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,  67.,
        68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,
        79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,
        90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.,
       101., 102., 103.])

In [ ]:
df[df['AGE']==-2].shape

(50, 14)

In [ ]:
df['AGE'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 4000 entries, 0 to 3999
Series name: AGE
Non-Null Count  Dtype  
--------------  -----  
4000 non-null   float64
dtypes: float64(1)
memory usage: 31.4 KB


In [ ]:
df['RIVERSIDE'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 4000 entries, 0 to 3999
Series name: RIVERSIDE
Non-Null Count  Dtype 
--------------  ----- 
4000 non-null   object
dtypes: object(1)
memory usage: 31.4+ KB


In [ ]:
df['RIVERSIDE'].unique()

array(['NO', 'UNKNOWN', 'YES'], dtype=object)

In [ ]:
df[df['RIVERSIDE']=='UNKNOWN'].shape

(88, 14)

In [ ]:
valid_data1 = df[(df['RIVERSIDE']!='UNKNOWN') & (df['AGE']!=-2)].copy()

In [ ]:
valid_data1[(valid_data1['RIVERSIDE']=='YES') & (valid_data1['AGE']<=50)].shape

(44, 14)

In [ ]:
df[df['HIGHWAYCOUNT'].isin([6,7,8])].shape

(1211, 14)

In [ ]:
df['CATEGORY'] =

In [ ]:
# prompt: Category 1: house price <10 lacs
# Category 2: 10 lacs <= house price <20 lacs
# Category 3: 20 lacs <= house price <30 lacs
# Category 4: 30 lacs <= house price <40 lacs
# Category 5: house price >=40 lacs
# pandas define a category based on above criteria
df['CATEGORY'] = pd.cut(df['PRICE'], bins=[0, 10, 20, 30, 40, float('inf')],
                       labels=['Category 1', 'Category 2', 'Category 3', 'Category 4', 'Category 5'], include_lowest=True)
df.head()

CRIM         ZN      INDUS  POLINDEX   RM   AGE        DIS  \
0   1.026769   1.429034   7.851300  1.134216  6.0  42.0   5.251911   
1   0.848089   0.255543   6.263434  1.245993  7.0  63.0   4.305546   
2  10.925905   0.441022  18.322960  2.824833  8.0  -2.0   2.409495   
3   0.559027   1.041175  11.114920  0.794952  6.0   9.0   6.898669   
4   0.905063  81.167963   3.673369  1.029030  8.0  20.0  10.246463   

   HIGHWAYCOUNT         TAX    PTRATIO         IMM        BPL      PRICE  \
0             5  279.201277  20.689586  398.811960  10.461456  22.991633   
1             8  307.444529  17.465398  377.153649  11.619690  24.551055   
2            25  666.492973  20.351601  387.061355  19.366070  15.875346   
3             4  305.514181  19.787314  391.778647   6.206820  23.007756   
4             1  315.913960  17.360439  395.833166  10.827105  21.503177   

  RIVERSIDE    CATEGORY  
0        NO  Category 3  
1        NO  Category 3  
2        NO  Category 2  
3        NO  Category 3  
4        NO  Category 3

In [ ]:
df['CATEGORY'].value_counts()

CATEGORY
Category 3    2028
Category 2    1158
Category 4     503
Category 5     268
Category 1      43
Name: count, dtype: int64

In [ ]:
valid_data2 = df.copy()

In [ ]:
import numpy as np
valid_data2["AGE"].replace(-2, np.nan, inplace=True)

In [ ]:
valid_data2["RIVERSIDE"].replace("UNKNOWN", np.nan, inplace=True)

In [ ]:
valid_data2["RM"].replace(-1, np.nan, inplace=True)

In [ ]:
valid_data2.columns

Index(['CRIM', 'ZN', 'INDUS', 'POLINDEX', 'RM', 'AGE', 'DIS', 'HIGHWAYCOUNT',
       'TAX', 'PTRATIO', 'IMM', 'BPL', 'PRICE', 'RIVERSIDE'],
      dtype='object')

In [ ]:
target_data = valid_data2['PRICE']

In [ ]:
features_data = valid_data2.drop(columns=['PRICE'])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features_data, target_data, test_size=0.3, random_state=0)

In [ ]:
y_train.shape

(2800,)

In [ ]:
y_test.shape

(1200,)

In [ ]:
X_train.shape

(2800, 13)

In [ ]:
X_test.shape

(1200, 13)

In [ ]:
valid_data3 = df.copy()

In [ ]:
valid_data3.columns

Index(['CRIM', 'ZN', 'INDUS', 'POLINDEX', 'RM', 'AGE', 'DIS', 'HIGHWAYCOUNT',
       'TAX', 'PTRATIO', 'IMM', 'BPL', 'PRICE', 'RIVERSIDE'],
      dtype='object')

2. CRIM: min max scaling
3. ZN: min max scaling
4. INDUS: standard scaling
5. POLINDEX: min max scaling
6. DIS: min max scaling
7. HIGHWAYCOUNT: min max scaling
8. TAX: min max scaling
9. PTRATIO: min max scaling
10. IMM: min max scaling
11. BPL: min max scaling
12. RM: impute with median then min max scaling
13. AGE: impute with mean then min max scaling
14. RIVERSIDE: Impute with most frequent value then one hot encode.


In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [ ]:
rm_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', MinMaxScaler())
])
age_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', MinMaxScaler())
])
riverside_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder())
])
min_max_columns = ['CRIM', 'ZN', 'POLINDEX', 'DIS', 'HIGHWAYCOUNT', 'TAX', 'PTRATIO', 'IMM', 'BPL']
std_columns = ['INDUS']
transformer = ColumnTransformer([
    ('rm_pipeline', rm_pipeline, ['RM']),
    ('age_pipeline', age_pipeline, ['AGE']),
    ('riverside_pipeline', riverside_pipeline, ['RIVERSIDE']),
    ('min_max_columns', MinMaxScaler(), min_max_columns),
    ('std_columns', StandardScaler(), std_columns)
])

In [ ]:
# prompt: np arrays to pd dataframe

transformed_data = transformer.fit_transform(X_test)
df_transformed = pd.DataFrame(transformed_data)
print(df_transformed.head())


         0         1    2    3         4         5         6         7   \
0  0.166667  0.969697  1.0  0.0  0.420574  0.009874  0.399706  0.034753   
1  0.500000  0.171717  1.0  0.0  0.131313  0.003189  0.498531  0.334632   
2  0.666667  0.515152  1.0  0.0  0.089137  0.280792  0.290630  0.220329   
3  0.333333  0.757576  1.0  0.0  0.056251  0.280016  0.108942  0.243937   
4  0.333333  0.929293  1.0  0.0  0.250744  0.004788  0.222853  0.056610   

         8         9         10        11        12        13  
0  0.192308  0.413165  0.305449  0.991607  0.840414  1.291900  
1  0.115385  0.224440  0.584996  0.941017  0.234261  0.112980  
2  0.115385  0.159865  0.615880  0.986406  0.198491  0.664609  
3  0.153846  0.158944  0.573659  0.995682  0.255640  0.565052  
4  0.153846  0.411066  0.258976  0.893758  0.852785  1.205215  


In [ ]:
df_transformed.shape

(1200, 14)

In [ ]:
df_transformed.mean().mean()

0.38536971806003834

In [1]:
import pandas as pd
df = pd.read_csv("NPPE1_ModelBuilding3.csv")
print(df.head())

          0         1         2         3         4         5         6  \
0  0.087472  0.002829  1.768235  0.188396  0.117071  0.148148  0.478165   
1  0.378379  0.022079  1.115629  0.091974  0.066089  0.851852  0.911759   
2  0.066901  0.003828 -0.536262  0.221188  0.255671  0.296296  0.228024   
3  0.140645  0.011132  1.323366  0.422514  0.153103  0.148148  0.410679   
4  0.144225  0.204918 -0.930790  0.148694  0.177490  0.259259  0.146832   

          7         8         9        10        11   12   13         14  
0  0.720443  0.967195  0.281563  0.428571  0.959596  1.0  0.0  23.358097  
1  0.785321  0.885001  0.424648  0.285714  0.868687  0.0  1.0  17.268768  
2  0.406472  0.980184  0.274376  0.428571  0.767677  0.0  1.0  27.776974  
3  0.200319  0.861371  0.305006  0.142857  0.848485  0.0  1.0  16.121960  
4  0.111429  0.983448  0.286322  0.285714  0.616162  1.0  0.0  23.129426  


In [4]:
target = df['14']
feature = df.drop(columns=['14'])

In [5]:
feature.head()

0         1         2         3         4         5         6  \
0  0.087472  0.002829  1.768235  0.188396  0.117071  0.148148  0.478165   
1  0.378379  0.022079  1.115629  0.091974  0.066089  0.851852  0.911759   
2  0.066901  0.003828 -0.536262  0.221188  0.255671  0.296296  0.228024   
3  0.140645  0.011132  1.323366  0.422514  0.153103  0.148148  0.410679   
4  0.144225  0.204918 -0.930790  0.148694  0.177490  0.259259  0.146832   

          7         8         9        10        11   12   13  
0  0.720443  0.967195  0.281563  0.428571  0.959596  1.0  0.0  
1  0.785321  0.885001  0.424648  0.285714  0.868687  0.0  1.0  
2  0.406472  0.980184  0.274376  0.428571  0.767677  0.0  1.0  
3  0.200319  0.861371  0.305006  0.142857  0.848485  0.0  1.0  
4  0.111429  0.983448  0.286322  0.285714  0.616162  1.0  0.0

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature, target, test_size=0.3, random_state=42)

In [7]:
from sklearn.linear_model import Ridge
ridge_model = Ridge(alpha=10, solver='saga', tol=1e-4, random_state=42)
ridge_model.fit(X_train, y_train)
ridge_model.score(X_test, y_test)

0.6613547575262211

In [8]:
ridge_model.coef_

array([ -0.4825441 ,   3.74601838,  -0.73583331,   0.54199933,
        -9.89014109,   5.80114296,  -5.06099736,  -9.45015598,
         4.73124885, -23.51321982,  11.31863371,   0.49450664,
        -0.89196134,   0.89196134])

In [10]:
# prompt: how to get best feature from the model? is it based on coeff?
import numpy as np
# Get the absolute values of coefficients
abs_coef = np.abs(ridge_model.coef_)

# Sort the coefficients in descending order and get the corresponding feature names
sorted_features = np.argsort(abs_coef)[::-1]
top_feature_names = feature.columns[sorted_features]

# Print the top features
print("Top features based on coefficient magnitude:")
for i, feature_name in enumerate(top_feature_names):
    print(f"{i+1}. {feature_name}: {abs_coef[sorted_features[i]]}")


Top features based on coefficient magnitude:
1. 9: 23.51321982201699
2. 10: 11.318633705726826
3. 4: 9.890141094536423
4. 7: 9.450155978660105
5. 5: 5.801142964333218
6. 6: 5.060997357617785
7. 8: 4.731248850376363
8. 1: 3.7460183831448557
9. 13: 0.8919613437096292
10. 12: 0.8919613437096292
11. 2: 0.7358333070898728
12. 3: 0.5419993325098258
13. 11: 0.4945066371456054
14. 0: 0.48254410388524144


In [12]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(random_state=42)

In [22]:
from sklearn.model_selection import GridSearchCV
penalty = ['l1', 'l2']
alpha = [1e-5, 1e-4, 1e-3, 1e-2, 1e-1]
tol = [1e-4, 1e-3, 1e-2, 1e-1]
grid_cv = GridSearchCV(sgd_reg, {'penalty': penalty, 'alpha': alpha, 'tol': tol}, cv=5, scoring='neg_mean_absolute_error')
grid_cv.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SGDRegressor(random_state=42),
             param_grid={'alpha': [1e-05, 0.0001, 0.001, 0.01, 0.1],
                         'penalty': ['l1', 'l2'],
                         'tol': [0.0001, 0.001, 0.01, 0.1]},
             scoring='neg_mean_absolute_error')

In [23]:
grid_cv.best_params_

{'alpha': 0.001, 'penalty': 'l2', 'tol': 0.0001}

In [24]:
y_pred = grid_cv.best_estimator_.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

3.8131121797994014

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Lasso
from sklearn.decomposition import PCA
pipeline = Pipeline([
    ('transformer', PCA()),
    ('estimator', Lasso())
])

In [27]:
n_components = [0.9, 0.95]
alpha = [10, 1, 0.01, 0.001]

In [28]:
grid_cv1 = GridSearchCV(pipeline, {'transformer__n_components': n_components, 'estimator__alpha': alpha}, cv=5, scoring='neg_mean_absolute_error', n_jobs=-1)
grid_cv1.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('transformer', PCA()),
                                       ('estimator', Lasso())]),
             n_jobs=-1,
             param_grid={'estimator__alpha': [10, 1, 0.01, 0.001],
                         'transformer__n_components': [0.9, 0.95]},
             scoring='neg_mean_absolute_error')

In [29]:
grid_cv1.score(X_test, y_test)

-4.010009320952856

In [32]:
best_pca = grid_cv1.best_estimator_.named_steps['transformer']

In [33]:
best_pca.explained_variance_ratio_

array([0.69937572, 0.09082355, 0.0680532 , 0.0421951 , 0.02324057,
       0.01665429, 0.01512212])

In [36]:
from sklearn.preprocessing import PolynomialFeatures
pipeline1 = Pipeline([
    ('transformer', PolynomialFeatures(interaction_only=False,degree=2)),
    ('estimator', Lasso(alpha=1,warm_start=True,random_state=0))
])

In [37]:
pipeline1.fit(X_train, y_train)

Pipeline(steps=[('transformer', PolynomialFeatures()),
                ('estimator', Lasso(alpha=1, random_state=0, warm_start=True))])

In [38]:
pipeline1.score(X_test, y_test)

0.157678032410551

In [39]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
rfe = RFE(estimator=LinearRegression(), n_features_to_select=X_train.shape[1] - 1)
rfe.fit(X_train, y_train)

RFE(estimator=LinearRegression(), n_features_to_select=13)

In [43]:
ranks = rfe.ranking_
ranks

array([1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
list(ranks).index(2)

2